[WIP] Quelques modifications sur la Table Of Contents
t00sh/mastercsi-per pull request #13
Opened 2019-02-13 16:36 UTC by t00sh

* Augmentation de la profondeur
    * Passage des commandes dans les titres en \emph{} qui donne un meilleur
      résultat visuel

Je la met en WIP, car il faut peut être pour être cohérent dans notre plan : 
- rajouter une subsection sur le "persistant mode" 
- découper davantage le chapitre 1 en subsection
- revoir le plan du chapitre 3, voir rajouter des sections

2019-02-13 16:46 UTC, Pamplemousse submitted a review, later dismissed

2019-02-13 17:06 UTC, Pamplemousse commented
Ah mince, j'avais pas fait attention au fait que c'était `[WIP]`.
Pourquoi ce statut ?

2019-02-13 17:07 UTC, t00sh commented
Pour le commentaire sur les choses à modifier.

Mais on peut merger, et modifier plus tard.

2019-02-13 18:04 UTC, t00sh commented
Quelques modifications du plan :
    
        - Ajout d'une partie sur le persistent mode (pas rédigée)
        - Ajout d'une partie sur les autres versions d'AFL (pas rédigée)
        - Modifications de quelques subsubsections en subsections
        - Ajout du chapter3.tex dans les dépendances du Makefile

2019-02-14 10:11 UTC, Pamplemousse submitted a review, later dismissed

2019-02-14 14:19 UTC, Pamplemousse requested changes

2019-02-14 14:19 UTC, Pamplemousse commented on report/chapter1.tex
> +\subsection{Le ``persistent mode''}\label{persistent-mode}
Ne pas le faire apparaitre tant qu'il sera pas rédigé : je préfère garder `master` comme une branche "production ready".
En plus, on a #15 qui référence cela.

2019-02-14 14:19 UTC, Pamplemousse commented on report/chapter3.tex
> +\section{Autres versions de AFL}
Même remarque.

2019-02-14 15:12 UTC, Pamplemousse approved these changes

2019-02-14 15:22 UTC, Gr0minet approved these changes

2019-02-14 15:22 UTC, merged