[slides] Modèle fork-server
t00sh/mastercsi-per pull request #26
Opened 2019-02-18 09:47 UTC by Pamplemousse

* comparaison entre approche "classique" et le fork-server :
    - une slide pleine de texte
    - une slide avec deux petits schémas
  * styliser \lstinline

2019-02-18 17:44 UTC, t00sh requested changes
Il manque tes images (classique.png et fork-server.png), à placer dans `medias`. Du coup, corriger aussi les chemins : 

`../medias/classique.png`, etc.

2019-02-18 17:46 UTC, Pamplemousse commented
Arf oui, les images sont bien dans `medias/`, mais les chemins ne sont pas bons...

2019-02-18 17:55 UTC, t00sh submitted a review, later dismissed

2019-02-19 14:14 UTC, Pamplemousse commented
Les schémas peuvent être un peu clarifiés / adaptés au format du support.

2019-02-19 15:15 UTC, Gr0minet submitted a review, later dismissed

2019-02-19 15:22 UTC, t00sh submitted a review, later dismissed

2019-02-19 15:23 UTC, t00sh approved these changes

2019-02-19 15:32 UTC, Gr0minet approved these changes

2019-02-19 15:32 UTC, merged