Chapitre 2 : rédaction de la partie "Analyse des résultats obtenus"
t00sh/mastercsi-per pull request #8
Opened 2019-02-11 22:27 UTC by t00sh

J'ai rédigé un peu la partie 2 du chapitre 2, en donnant une analyse des différents problèmes que nous avons trouvés et remontés.

C'est peut être "too much", je n'en sais rien. Je vous laisse juger et donner votre avis !

2019-02-12 09:39 UTC, Pamplemousse requested changes

2019-02-12 09:39 UTC, Pamplemousse commented on report/chapter2.tex
> +            /* ... */
L'indentation des commentaires rajoutées est inconsistente.

2019-02-12 09:39 UTC, Pamplemousse commented on report/chapter2.tex
> +            /* free 1 */
Ditto.

2019-02-12 09:39 UTC, Pamplemousse commented on report/chapter2.tex
> +          /* free 1-bis */
Ditto.

2019-02-12 09:39 UTC, Pamplemousse commented on report/chapter2.tex
> +
On devrait mentionner que c'est nous qui avons annoté les citations de code en ajoutant des commentaires.
Quitte à mettre une note disant que cela concerne toutes les citations.
Et pourquoi pas avec une petite légende, par exemple : "Pour raccourcir les citations, nous avons remplacé des portions de code non pertinentes dans notre analyse par des '/* ... */'".

2019-02-12 09:40 UTC, Pamplemousse commented
C'est excellent !
Le petit tableau récapitulatif à la fin :+1: .

2019-02-12 09:47 UTC, t00sh commented on report/chapter2.tex
> +            /* free 1 */
Normalement corrigé dans 5718559

2019-02-12 09:47 UTC, t00sh commented on report/chapter2.tex
> +            /* ... */
Normalement corrigé dans 5718559

2019-02-12 09:49 UTC, t00sh commented on report/chapter2.tex
> +          /* free 1-bis */
Normalement corrigé dans 5718559

2019-02-12 17:28 UTC, t00sh commented on report/chapter2.tex
> +
J'ai rajouté une footnote dans 0966910, dis moi si ça te conviens.

2019-02-13 08:47 UTC, Pamplemousse approved these changes

2019-02-13 15:15 UTC, Gr0minet approved these changes

2019-02-13 15:17 UTC, merged